### PR TITLE
user now only need to configure find and replace stuff

### PR DESCRIPTION
**Pull request by ghost**
I just made it so that the user would call the seed.sh and pass to it the address of the remote like so:
`./seed.sh https://github.com/username/myproject.git`

and then the project name would be extracted from that address. `myproject`

if you decide that this is a good commit, you may want to modify the README.md accordingly.

### CODE REVIEW

**Comment by ghost** [comment]
oh and by the way. it handles both ssh and https links

**Comment by AmrAbdulrahman** [comment]
Hi Adam,

Thank you so much for the changes.
I like it, more usable like that.

Here's my only thought:
- please update the README

Thanks again,

**Comment by ghost** [comment]
1. Alright, so I've added input validation so that if user doesn't enter the remote the script would exit.
2. and if the user enters a remote without the `.git` extension the script would add it automatically.
3. The configuration in the script has been moved to the very beginning of the script for better usability.
4. README.md has been modified accordning to changes.

**Comment by AmrAbdulrahman** [comment]
Well done Adam!

**Comment by ghost** [comment]
Thank you :D

**Pull request merged**
